ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: api.conductor.fcortes.com.br
      paths:
        - path: "/"
  tls:
   - secretName: quarkus-demo-tls
     hosts:
       - api.conductor.fcortes.com.br
