{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-demo.fullname" . }}
  labels:
    {{- include "quarkus-demo.labels" . | nindent 4 }}
type: Opaque
data:
  DB_URL: {{ .Values.secret.data.DB_URL | b64enc | quote }}
  DB_USER: {{ .Values.secret.data.DB_USER | b64enc | quote }}
  DB_PASS: {{ .Values.secret.data.DB_PASS | b64enc | quote }}
{{- end }}
